apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: cdviz
build:
  artifacts:
    - image: ghcr.io/davidb/cdviz-collector
      docker:
        dockerfile: Dockerfile
        target: cdviz-collector
        cacheFrom:
          # Local Docker builder replaces cache references to the artifact image with
          # the tagged image reference, useful for caching from the previous build.
          - ghcr.io/davidb/cdviz-collector
    - image: ghcr.io/davidb/cdviz-dbmigration
      docker:
        dockerfile: Dockerfile
        target: cdviz-dbmigration
        cacheFrom:
          # Local Docker builder replaces cache references to the artifact image with
          # the tagged image reference, useful for caching from the previous build.
          - ghcr.io/davidb/cdviz-dbmigration
  local:
    useDockerCLI: false
    useBuildkit: true

deploy:
  helm:
    releases:
      - name: cdviz
        namespace: cdviz
        createNamespace: true
        chartPath: charts/cdviz
        valuesFiles:
          - charts/cdviz/values.yaml
        version: 0.1.0
        setValueTemplates:
          cdviz-collector.image.repository: "{{.IMAGE_REPO_ghcr_io_davidb_cdviz_collector}}"
          cdviz-collector.image.tag: "{{.IMAGE_TAG_ghcr_io_davidb_cdviz_collector}}@{{.IMAGE_DIGEST_ghcr_io_davidb_cdviz_collector}}"
          cdviz-collector.dbMigration.image.repository: "{{.IMAGE_REPO_ghcr_io_davidb_cdviz_dbmigration}}"
          cdviz-collector.dbMigration.image.tag: "{{.IMAGE_TAG_ghcr_io_davidb_cdviz_dbmigration}}@{{.IMAGE_DIGEST_ghcr_io_davidb_cdviz_dbmigration}}"
        setValues:
          postgresql.enabled: true
          grafana.enabled: true
          grafanaAssets.enabled: true
