version: "3"

includes:
  # default:
  #   cmds:
  #     - task --list-all
  cdviz-db:
    taskfile: ./cdviz-db/taskfile.yaml
    dir: ./cdviz-db
  cdviz-collector:
    taskfile: ./cdviz-collector/taskfile.yaml
    dir: ./cdviz-collector
  cdviz-site:
    taskfile: ./cdviz-site/taskfile.yaml
    dir: ./cdviz-site
  charts:
    taskfile: ./charts/taskfile.yaml
    dir: ./charts
