[sinks.debug]
type = "debug"

[sinks.cdviz_db]
type = "db"
url = "postgresql://cdviz:postgres-password@127.0.0.1:5432/cdviz"
pool_connections_min = 1
pool_connections_max = 10

[sources.cdevents_folder]
type = "opendal"
kind = "fs"
polling_interval = "10s"
parameters = { root = "./cdevents" }
