{{- if .Values.secrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}-su
  labels:
    {{- include "my.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: |-
    {{ .Values.secrets.values.DATABASE_URL | default (printf "postgres://%s:%s@%s:%s/%s" .Values.secrets.values.CDVIZ_SU_POSTGRES_USER .Values.secrets.values.CDVIZ_SU_POSTGRES_PASSWORD .Values.secrets.values.POSTGRES_HOST .Values.secrets.values.POSTGRES_PORT_NUMBER .Values.secrets.values.POSTGRES_DB) | b64enc }}
  POSTGRES_USER: |-
    {{ .Values.secrets.values.CDVIZ_SU_POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: |-
    {{ .Values.secrets.values.CDVIZ_SU_POSTGRES_PASSWORD | b64enc }}
  POSTGRES_HOST: |-
    {{ .Values.secrets.values.POSTGRES_HOST | b64enc }}
  POSTGRES_PORT_NUMBER: |-
    {{ .Values.secrets.values.POSTGRES_PORT_NUMBER | b64enc }}
  POSTGRES_DB: |-
    {{ .Values.secrets.values.POSTGRES_DB | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}-rw
  labels:
    {{- include "my.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: |-
    {{ .Values.secrets.values.DATABASE_URL | default (printf "postgres://%s:%s@%s:%s/%s" .Values.secrets.values.CDVIZ_RW_POSTGRES_USER .Values.secrets.values.CDVIZ_RW_POSTGRES_PASSWORD .Values.secrets.values.POSTGRES_HOST .Values.secrets.values.POSTGRES_PORT_NUMBER .Values.secrets.values.POSTGRES_DB) | b64enc }}
  POSTGRES_USER: |-
    {{ .Values.secrets.values.CDVIZ_RW_POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: |-
    {{ .Values.secrets.values.CDVIZ_RW_POSTGRES_PASSWORD | b64enc }}
  POSTGRES_HOST: |-
    {{ .Values.secrets.values.POSTGRES_HOST | b64enc }}
  POSTGRES_PORT_NUMBER: |-
    {{ .Values.secrets.values.POSTGRES_PORT_NUMBER | b64enc }}
  POSTGRES_DB: |-
    {{ .Values.secrets.values.POSTGRES_DB | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}-ro
  labels:
    {{- include "my.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: |-
    {{ .Values.secrets.values.DATABASE_URL | default (printf "postgres://%s:%s@%s:%s/%s" .Values.secrets.values.CDVIZ_RO_POSTGRES_USER .Values.secrets.values.CDVIZ_RO_POSTGRES_PASSWORD .Values.secrets.values.POSTGRES_HOST .Values.secrets.values.POSTGRES_PORT_NUMBER .Values.secrets.values.POSTGRES_DB) | b64enc }}
  POSTGRES_USER: |-
    {{ .Values.secrets.values.CDVIZ_RO_POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: |-
    {{ .Values.secrets.values.CDVIZ_RO_POSTGRES_PASSWORD | b64enc }}
  POSTGRES_HOST: |-
    {{ .Values.secrets.values.CDVIZ_RO_POSTGRES_HOST | default .Values.secrets.values.POSTGRES_HOST | b64enc }}
  POSTGRES_PORT_NUMBER: |-
    {{ .Values.secrets.values.CDVIZ_RO_POSTGRES_PORT_NUMBER | default .Values.secrets.values.POSTGRES_PORT_NUMBER | b64enc }}
  POSTGRES_DB: |-
    {{ .Values.secrets.values.POSTGRES_DB | b64enc }}
{{- end }}
