# version: "3.9"
services:
  #region database
  postgres:
    image: ghcr.io/cdviz-dev/cdviz-db-pg:latest
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]
    # restart: always
    # platform: linux/amd64
    shm_size: 128mb
    environment:
      POSTGRES_USER: cdviz
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: cdviz
    healthcheck:
      test: pg_isready -U cdviz -d cdviz
      interval: 10s
      timeout: 5s
      retries: 5
    # network_mode: host
    ports:
      - "5432:5432"
    # user: "${MY_UID:-1000}:${MY_GID:-1000}"
    # volumes:
      # # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path
      # # It means that every time the repository is modifying the data inside
      # # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`
      # # You don't need to create the `db-data` folder. Docker Compose will do it for you
      # - ./tmp/postgres/data:/var/lib/postgresql/data
      # # In this example, we share an init.sql script with the container
      # # The init script will be executed when the database is first run
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  cdviz-db-migrate:
    image: ghcr.io/cdviz-dev/cdviz-db-migration:latest
    command:
      - migrate
      - apply
      - --url
      - postgres://cdviz:postgres-password@postgres:5432/cdviz?sslmode=disable
      - --dir
      - file:///migrations/
    # network_mode: host
    depends_on:
      postgres:
        condition: service_healthy
  #endregion database
  #region grafana
  grafana:
    image: docker.io/grafana/grafana-oss:12.1.0
    # container_name: grafana
    # restart: unless-stopped
    environment:
      # see https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
      # To override an option, use a predefined pattern GF_<SectionName>_<KeyName>.
      # - GF_SERVER_ROOT_URL=http://my.grafana.server/
      # - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel,volkovlabs-form-panel,volkovlabs-table-panel
      # - GF_SECURITY_ADMIN_USER=admin
      # - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_DISABLE_SIGNOUT_MENU=true
      # - GF_SECURITY_ALLOW_EMBEDDING=true #Allow IFRAME Calls
      - GF_PANELS_DISABLE_SANITIZE_HTML=true # Allow html, svg, ... into business text,...
      - GF_ENABLE_GZIP=true
      - CDVIZ_RO_POSTGRES_HOST=postgres
      - CDVIZ_RO_POSTGRES_PORT_NUMBER=5432
      - CDVIZ_RO_POSTGRES_USER=cdviz
      - CDVIZ_RO_POSTGRES_PASSWORD=postgres-password
      - CDVIZ_RO_POSTGRES_DB=cdviz
    # network_mode: host
    ports:
      - "3000:3000"
    # user: "${MY_UID:-1000}:${MY_GID:-1000}"
    volumes:
      # - ./tmp/grafana/data/:/var/lib/grafana/:rw
      - ../../cdviz-grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ../../cdviz-grafana/dashboards:/var/provisioning/dashboards:rw
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      # - ./tmp/grafana.ini:/etc/grafana/grafana.ini
  # endregion grafana

  # region cdviz-collector
  cdviz-collector:
    image: ghcr.io/cdviz-dev/cdviz-collector:latest
    command:
      - connect
      - -vv
      - --directory
      - /var/use_cases
      - --config
      - ./cdviz-collector.toml
    # restart: unless-stopped
    environment:
      - CDVIZ_COLLECTOR__HTTP__PORT=8080
      - CDVIZ_COLLECTOR__SINKS__DEBUG__ENABLED=true
      - CDVIZ_COLLECTOR__SINKS__CDVIZ_DB__ENABLED=true
      - CDVIZ_COLLECTOR__SINKS__CDVIZ_DB__URL=postgres://cdviz:postgres-password@postgres:5432/cdviz?sslmode=disable
      - CDVIZ_COLLECTOR__SOURCES__CDEVENTS_WEBHOOK__ENABLED=true
      - CDVIZ_COLLECTOR__SOURCES__CDEVENTS_WEBHOOK__EXTRACTOR__ID=000-cdevents
      - CDVIZ_COLLECTOR__SOURCES__CDEVENTS_LOCAL_JSON__ENABLED=false
    # network_mode: host
    ports:
      - "8080:8080"
    # user: "${MY_UID:-1000}:${MY_GID:-1000}"
    volumes:
      # - ./tmp/cdviz-collector:/var/cdviz-collector:ro
      - ../use_cases:/var/use_cases:rw
    depends_on:
      postgres:
        condition: service_healthy
      cdviz-db-migrate:
        condition: service_completed_successfully

  # endregion cdviz-collector
