apiVersion: v2
name: cdviz-collector
description: A Helm chart for Kubernetes
type: application
version: 0.0.0 # version set during release
icon: https://cdviz.dev/assets/favicon.svg
keywords:
  - sdlc
  - cd
home: https://cdviz.dev/
sources:
  - https://github.com/cdviz-dev/cdviz
