apiVersion: v2
name: cdviz-collector
description: Helm chart for cdviz-collector - Event collection service for CDEvents and CI/CD pipeline observability
type: application
version: 0.0.0 # version set during release
icon: https://cdviz.dev/assets/favicon.svg
keywords:
  - sdlc
  - cd
home: https://cdviz.dev/
sources:
  - https://github.com/cdviz-dev/cdviz

dependencies:
  - name: kubewatch
    version: 3.5.0
    repository: https://robusta-charts.storage.googleapis.com
    condition: kubewatch.enabled
