apiVersion: v2
name: cdviz-collector
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: 13.2.27
    # repository: https://charts.bitnami.com/bitnami
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
