apiVersion: v2
name: cdviz-collector
description: A Helm chart for Kubernetes
type: application
version: 0.2.0 # TODO Change this to a version number on release
appVersion: 0.2.0 # TODO Change this to a version number on release
