version: '3'

tasks:

  plan:
    desc: "update the migrations to reflect target `src/schema.sql`"
    cmds:
      - atlas migrate diff --env local
      - atlas migrate lint --env local --latest 2
      - atlas migrate validate --env local

  apply:
    desc: "apply the schema & data migrations"
    # cmd: atlas schema apply --env local
    cmd: atlas migrate apply --env local

  db-local:start-empty:
    desc: "start a container for the local db (empty: no data, no schema)"
    cmd: docker run --name cdviz-db -e "POSTGRES_PASSWORD=$PG_LOCAL_PWD" -e "POSTGRES_USER=$PG_LOCAL_USER" -p 5432:5432 -d postgres:16.1

  db-local:start:
    desc: "start a container for the local db with the migrations applied"
    cmds:
      - docker run --name cdviz-db -e "POSTGRES_PASSWORD=$PG_LOCAL_PWD" -e "POSTGRES_USER=$PG_LOCAL_USER" -p 5432:5432 -d postgres:16.1
      - sleep 6
      - task: apply

  db-local:stop:
    desc: "stop the container of the local db"
    cmd: docker rm -f cdviz-db

  test:
    cmds:
      - task: db-local:start
      - task: db-local:stop