# Grafana datasources configuration
datasources:
  enabled: false  # Set to true to create datasource configmaps
  annotations:
    grafana_datasource: "1"
  definitions:
    cdviz-db:
      enabled: false # enable/disable the datasource
      # Grafana datasource configuration (same syntax as Grafana provisioning)
      type: postgres
      access: proxy
      url: 'postgresql://host:5432'  # Override with actual database URL
      user: 'cdviz'  # Database username
      secureJsonData:
        password: 'your-password'  # Database password
      jsonData:
        database: 'cdviz'  # Database name
        sslmode: 'disable' # disable/require/verify-ca/verify-full
        maxOpenConns: 10 # Grafana v5.4+
        maxIdleConns: 10 # Grafana v5.4+
        maxIdleConnsAuto: true # Grafana v9.5.1+
        connMaxLifetime: 14400 # Grafana v5.4+
        postgresVersion: 1600  # PostgreSQL version (1200=12, 1300=13, 1400=14, 1500=15, 1600=16)
        timescaledb: true

# Grafana dashboards configuration
dashboards:
  enabled: true  # Set to true to create dashboard configmaps
  annotations:
    grafana_dashboard: "1"

# Additional kubernetes resources to create. Helm template could be used.
# you could use it to create secrets, external secrets,
# configmaps, gateways (http-route, filter, ...), volumes, keda, ...
# - the name/key of the resource is used just to access the definition more easily than an arrays's index
# - the 'enabled' field is used to enable/disable the resource (removed when the resource is templated)
# - user can add any other resource definition as child node of extraObjects
# The manifests can be defined as a string or as a dictionary. But the string doesn't use the 'enabled' field.
extraObjects: {}
  # extrernalSecrets:
  #   enabled: true
  #   apiVersion: "kubernetes-client.io/v1"
  #   kind: ExternalSecret
  #   metadata:
  #     name: cdviz-collector-secrets
  #   spec:
  #     backendType: gcpSecretsManager
  #     data:
  #       - key: api-token
  #         name: api-token
