apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: cdviz
build:
  artifacts:
    - image: ghcr.io/cdviz-dev/cdviz-collector
      context: ../cdviz-collector
      docker:
        dockerfile: ../cdviz-collector/Dockerfile
        target: cdviz-collector
        cacheFrom:
          # Local Docker builder replaces cache references to the artifact image with
          # the tagged image reference, useful for caching from the previous build.
          - ghcr.io/cdviz-dev/cdviz-collector
    - image: ghcr.io/cdviz-dev/cdviz-db
      context: ../cdviz-db
      docker:
        dockerfile: ../cdviz-db/Dockerfile
        target: cdviz-db
        cacheFrom:
          # Local Docker builder replaces cache references to the artifact image with
          # the tagged image reference, useful for caching from the previous build.
          - ghcr.io/cdviz-dev/cdviz-db
  local:
    useDockerCLI: false
    useBuildkit: true

deploy:
  helm:
    releases:
      - name: cdviz
        namespace: cdviz-dev
        createNamespace: true
        chartPath: ../charts/cdviz
        valuesFiles:
          - ../charts/cdviz/values.yaml
        version: 0.0.0
        setValueTemplates:
          cdviz-collector.image.repository: "{{.IMAGE_REPO_ghcr_io_davidb_cdviz_collector}}"
          cdviz-collector.image.tag: "{{.IMAGE_TAG_ghcr_io_davidb_cdviz_collector}}@{{.IMAGE_DIGEST_ghcr_io_davidb_cdviz_collector}}"
          cdviz-db.image.repository: "{{.IMAGE_REPO_ghcr_io_davidb_cdviz_db}}"
          cdviz-db.image.tag: "{{.IMAGE_TAG_ghcr_io_davidb_cdviz_db}}@{{.IMAGE_DIGEST_ghcr_io_davidb_cdviz_db}}"
        setValues:
          cdviz-db.enabled: true
          cdviz-collector.enabled: true
          cdviz-grafana.enabled: true
          postgresql.enabled: true
          grafana.enabled: true
          grafanaAssets.enabled: true
