apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my.fullname" . }}
data:
{{ (.Files.Glob "config_files/**").AsConfig | indent 2 }}
{{- range $path, $content :=  .Values.configFiles }}
  {{ $path | quote }}: |
    {{ $content | nindent 4 }}
{{- end }}
