[sinks.debug]
enabled = true

[sinks.cdviz_db]
enabled = false

[sources.cdevents_webhook]
enabled = false

[sources.cdevents_webhook.extractor]
type = "webhook"
id = "000"

[sources.github_webhook]
enabled = false

[sources.github_webhook.extractor]
type = "webhook"
id = "001"
headers_to_keep = []
signature = { signature_encoding = "hex", signature_on = "body", signature_prefix = "sha256=", header = "x-hub-signature-256", token = "changeme" }

[transformers.github_events]
type = "vrl"
template_file = "./cnv_github_events.vrl"
