apiVersion: v2
name: cdviz
description: A Helm chart for Kubernetes
type: application
version: 0.1.0 # TODO Change this to a version number on release
appVersion: 0.1.0 # TODO Change this to a version number on release

dependencies:
  - name: postgresql
    version: 15.2.2
    # repository: https://charts.bitnami.com/bitnami
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: grafana
    version: 7.3.9 # grafana 10.2.2
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: cdviz-collector
    version: 0.1.0
    repository: file://../cdviz-db
    condition: cdviz-db.enabled
  - name: cdviz-collector
    version: 0.1.0
    repository: file://../cdviz-collector
    condition: cdviz-collector.enabled
  - name: cdviz-grafana
    version: 0.1.0
    repository: file://../cdviz-grafana
    condition: cdviz-grafana.enabled
