ttlSecondsAfterFinished: 7200
image:
  repository: ghcr.io/cdviz-dev/cdviz-db
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""
annotations: {}
  # "helm.sh/hook": post-install,post-upgrade
  # "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

env:
  # DATABASE_URL children node could be any env's value definition supported by kubernetes's pod manifest
  # helm template could be used
  DATABASE_URL:
    valueFrom:
      secretKeyRef:
        name: ""
        key: DATABASE_URL

# Additional kubernetes resources to create. Helm template could be used.
# you could use it to create secrets, or custom resources like external secrets,
# database definitions for an operator,...
# apiVersion: postgresql.cnpg.io/v1
extraResources: []
