ttlSecondsAfterFinished: 7200
image:
  repository: ghcr.io/davidb/cdviz-db
  pullPolicy: IfNotPresent
  tag: "latest" # TODO Change this to a version number on release
annotations: {}
  # "helm.sh/hook": post-install,post-upgrade
  # "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

env:
  # DATABASE_URL children node could be any env's value definition supported by kubernetes's pod manifest
  # helm template could be used
  DATABASE_URL:
    valueFrom:
      secretKeyRef:
        name: "{{ .Values.secrets.name }}"
        key: DATABASE_URL

# Secrets is also used to store configuration
# For production, you should create a secrets (encrypted or from an external source)
# see Chart of cdviz for more details (list of keys,...)
secrets:
  name: cdviz-su
