ttlSecondsAfterFinished: 7200
image:
  repository: ghcr.io/cdviz-dev/cdviz-db
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""
annotations: {}
  # "helm.sh/hook": post-install,post-upgrade
  # "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

env:
  # DATABASE_URL children node could be any env's value definition supported by kubernetes's pod manifest
  # helm template could be used
  DATABASE_URL:
    valueFrom:
      secretKeyRef:
        name: ""
        key: DATABASE_URL

# Additional kubernetes resources to create. Helm template could be used.
# you could use it to create secrets, or custom resources like external secrets,
# configmaps, gateways, volumes, keda, ...
# - the name/key of the resource is used just to access the definition more easily than an arrays's index
# - the 'enabled' field is used to enable/disable the resource (removed when the resource is templated)
# - user can add any other resource definition as child node of extraResources
extraResources:
  cloudnative-pg-basic:
    enabled: false
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: cdviz-db
    spec:
      instances: 1
      storage:
        size: 100Mi
      monitoring:
        enablePodMonitor: true
      bootstrap:
        initdb:
          database: cdviz
          owner: cdviz
          secret:
            name: cdviz-db-owner-secret
  cdviz-db-owner-secret:
    enabled: false
    apiVersion: v1
    kind: Secret
    metadata:
      name: cdviz-db-owner-secret
    type: kubernetes.io/basic-auth
    data:
      username: '{{ "cdviz-su" b64enc }}'
      password: '{{ "mysecretpassword" | b64enc }}'
