ttlSecondsAfterFinished: 7200
image:
  repository: ghcr.io/cdviz-dev/cdviz-db-migration
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "0.20250607150000.0"
annotations: {}
  # "helm.sh/hook": post-install,post-upgrade
  # "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

env:
  # DATABASE_URL children node could be any env's value definition supported by kubernetes's pod manifest
  # helm template could be used
  # Example configurations:
  # 1. Reference existing secret:
  #    DATABASE_URL:
  #      valueFrom:
  #        secretKeyRef:
  #          name: "my-database-secret"
  #          key: DATABASE_URL
  # 2. Direct value (not recommended for production):
  #    DATABASE_URL:
  #      value: "postgresql://user:pass@host:5432/cdviz"
  DATABASE_URL:
    valueFrom:
      secretKeyRef:
        name: "cdviz-db-secret"
        key: DATABASE_URL

# Additional kubernetes resources to create. Helm template could be used.
# you could use it to create secrets, external secrets,
# configmaps, gateways (http-route, filter, ...), volumes, keda, ...
# - the name/key of the resource is used just to access the definition more easily than an arrays's index
# - the 'enabled' field is used to enable/disable the resource (removed when the resource is templated)
# - user can add any other resource definition as child node of extraObjects
# The manifests can be defined as a string or as a dictionary. But the string doesn't use the 'enabled' field.
extraObjects:
  cloudnative-pg-basic:
    enabled: false
    apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: cdviz-db
    spec:
      instances: 1
      # PostgreSQL image with TimescaleDB extension
      # PG 17.4 support is available but may have compatibility issues
      imageName: ghcr.io/cdviz-dev/cdviz-db-pg:17.2
      imagePullPolicy: IfNotPresent
      # postgresUID: 26
      # postgresGID: 26
      postgresql:
        shared_preload_libraries:
          - timescaledb
        # Parameters configuration will be append
        # to the default ones to make the cluster work
        # parameters:
        #   auto_explain.log_min_duration: "10s"
      bootstrap:
        initdb:
          database: cdviz
          owner: cdviz
          secret:
            name: cdviz-db-owner-secret
          postInitTemplateSQL:
            - CREATE EXTENSION IF NOT EXISTS timescaledb;
            - CREATE EXTENSION IF NOT EXISTS timescaledb_toolkit;
      storage:
        size: 100Mi
      monitoring:
        enablePodMonitor: true
  cdviz-db-owner-secret:
    enabled: false
    apiVersion: v1
    kind: Secret
    metadata:
      name: cdviz-db-owner-secret
    type: kubernetes.io/basic-auth
    data:
      username: '{{ "cdviz-su" | b64enc }}'
      password: '{{ "mysecretpassword" | b64enc }}'
