[tools]
"ubi:cdviz-dev/cdviz-collector" = "latest"

[tasks."run"]
description = "Launch cdviz-collector cli with content (data & configuration) of the use_cases folder"
env = { OTEL_TRACES_SAMPLER = "always_off", OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = "http://127.0.0.1:4317", CDVIZ_COLLECTOR__SINKS__DEBUG__ENABLED = "false" }
run = [
  "cdviz-collector connect -vv --config ./cdviz-collector.toml",
  # - export UID=$(id -u)
  # - export GID=$(id -g)
  # - echo ">> $UID -- $GID"
  # - mkdir -p tmp/grafana/data || true
  # RUST_LOG: "cdviz_collector::sinks=debug,info" # cdviz_collector::sources=debug
]
