{
 "title": "CDEvents Activity",
 "tags": [ "cdevents" ],
 "time": { "from": "now-31d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   {
    "name": "subjects",
    "label": "Subjects",
    "query": "SELECT DISTINCT \"subject\"\nFROM cdviz.\"cdevents_lake\"\nWHERE $__timeFilter(timestamp)"
   },
   {
    "name": "predicates",
    "label": "Predicates",
    "query": "SELECT DISTINCT \"predicate\"\nFROM cdviz.\"cdevents_lake\"\nWHERE $__timeFilter(timestamp)\n  AND \"subject\" = ANY(ARRAY[${subjects:sqlstring}]::text[])"
   },
   { "name": "pageSize" },
   { "name": "offset" }
  ]
 },
 "panels": [
  {
   "title": "How many events?",
   "type": "volkovlabs-echarts-panel",
   "description": "Count by Subject & Predicate over the time window",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) as count,\n  subject || '/' || predicate as path\nFROM cdviz.cdevents_lake\nWHERE $__timeFilter(timestamp)\n  AND subject = ANY(ARRAY[${subjects:sqlstring}]::text[])\n  AND predicate = ANY(ARRAY[${predicates:sqlstring}]::text[])\nGROUP BY subject, predicate\nORDER BY subject, predicate"
    }
   ]
  },
  {
   "title": "Events By Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('1 hour', timestamp) AS time,\n  (subject || '/' || predicate) AS kind,\n  COUNT(*)\nFROM cdviz.cdevents_lake\nWHERE $__timeFilter(timestamp)\n  AND subject = ANY(ARRAY[${subjects:sqlstring}]::text[])\n  AND predicate = ANY(ARRAY[${predicates:sqlstring}]::text[])\nGROUP BY time, kind\nORDER BY time, kind"
    }
   ]
  },
  {
   "title": "How many sources?",
   "type": "volkovlabs-echarts-panel",
   "description": "Count by Context'source over the time window",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) as count,\n  \"payload\" -> 'context' ->> 'source' as \"path\"\nFROM cdviz.cdevents_lake\nWHERE $__timeFilter(timestamp)\n  AND subject = ANY(ARRAY[${subjects:sqlstring}]::text[])\n  AND predicate = ANY(ARRAY[${predicates:sqlstring}]::text[])\nGROUP BY path\nORDER BY path"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "x": 0, "y": 8, "h": 1, "w": 24 } },
  {
   "title": "Events Logs",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\",\n  \"subject\",\n  \"predicate\",\n  (\"payload\" -> 'subject')::text as \"payload_subject\",\n  (\"payload\" -> 'context')::text as \"payload_context\",\n  (\"payload\" -> 'customData')::text as \"payload_custom\",\n  \"imported_at\"\nFROM\n  cdviz.cdevents_lake\nWHERE\n  $__timeFilter(timestamp)\n  AND subject = ANY(ARRAY[${subjects:sqlstring}]::text[])\n  AND predicate = ANY(ARRAY[${predicates:sqlstring}]::text[])\nORDER BY\n  imported_at DESC\nLIMIT\n  ${pageSize}\nOFFSET\n  ${offset}"
    }
   ]
  }
 ]
}