name: release

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  # id-token: write

jobs:
  publish:
    # Only run if the commit message starts with "chore(release):"
    if: startsWith(github.event.head_commit.message, 'chore(release):') || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Full history needed for git tags and git describe
      - run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
        shell: bash
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx # to support buildx, multi-arch builds
        uses: docker/setup-buildx-action@v3
      - uses: jdx/mise-action@v3
        with:
          experimental: true
      - run: mise run '//cdviz-db:publish'
        shell: bash
      - run: mise run //charts:release_publish
        shell: bash
