name: release

on:
  push:
    # branches:
    #   - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  # id-token: write

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v5
        with:
          fetch-depth: "0" # to be able to use `git describe` and retrieve tags

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up Docker Buildx # to support buildx, multi-arch builds
        uses: docker/setup-buildx-action@v3
      - uses: jdx/mise-action@v3
      - run: mise install # cdviz-db
        shell: bash
        working-directory: cdviz-db
      - run: mise run publish # cdviz-db
        shell: bash
        working-directory: cdviz-db
      - run: mise install # charts
        shell: bash
        working-directory: charts
      - run: mise run publish  # charts
        shell: bash
        working-directory: charts
