name: Publish Chart Releases

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish:
    # Only run if the commit message starts with "chore(release):"
    if: startsWith(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Full history needed for git tags

      - name: Install mise
        uses: jdx/mise-action@v3
        with:
          experimental: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx # to support buildx, multi-arch builds
        uses: docker/setup-buildx-action@v3
      - name: Publish charts
        run: mise run //charts:release_publish
        shell: bash
